<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav</name>
   <tag></tag>
   <elementGuidId>504e22f1-e2f4-4ad9-a5cd-36dcf5e4849b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>nav.fixed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>nav.fixed</value>
   </webElementProperties>
</WebElementEntity>
