<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_tesuuryou_jouhou</name>
   <tag></tag>
   <elementGuidId>30c93b4a-fbcf-4a60-99fe-cfb33f69d6ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[contains(.,'手数料情報')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[contains(.,'手数料情報')]</value>
   </webElementProperties>
</WebElementEntity>
