<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kaiyakuji_shintaku_zaisan_ryuuhogaku</name>
   <tag></tag>
   <elementGuidId>6959b681-2c7e-4b11-8e38-84fc7031a96b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(.,'解約時信託財産留保額')]/following-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(.,'解約時信託財産留保額')]/following-sibling::td[1]</value>
   </webElementProperties>
</WebElementEntity>
