<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kaiyakuji_tesuuryou_gaku</name>
   <tag></tag>
   <elementGuidId>52ba59e5-015c-4eae-b98f-99d0bf9c94dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(.,'解約時手数料額')]/following-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(.,'解約時手数料額')]/following-sibling::td[1]</value>
   </webElementProperties>
</WebElementEntity>
