<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kounyuuji_shintaku_zaisan_ryuuhogaku</name>
   <tag></tag>
   <elementGuidId>b1e1d07e-5f4e-4604-8c7a-717facbd7698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(.,'購入時信託財産留保額')]/following-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(.,'購入時信託財産留保額')]/following-sibling::td[1]</value>
   </webElementProperties>
</WebElementEntity>
