<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kounyuuji_tesuuryou_gaku</name>
   <tag></tag>
   <elementGuidId>f564a37a-a7b4-4f8f-a044-339a09c89d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(.,'購入時手数料額')]/following-sibling::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(.,'購入時手数料額')]/following-sibling::td[1]</value>
   </webElementProperties>
</WebElementEntity>
